### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by erinleeme** [RHEMA-App/rhema-be#2]
@ujgon 
- @Id 어노테이션 import가 왜 springframework.data.annotation.Id 로 들어가있을까요~?
- Song Entity의 Section 컬럼 타입이 왜 enum일까요?

**Comment by ujgon** [comment]
1. @ID 어노테이션은 NoSQL 에서 지원하는 Spring Data 프로젝트에서 사용된다. (Ex) MongoDB)
우리가 쓸 PostgreSQL은 관계형 데이터베이스로 직접적으로 필요하지 않다.

2. enum은 열거형 타입을 의미함
@Enumerated 는 JPA에서 enum 타입을 데이터베이스에 저장할때 사용하는 에너테이션.

section이라는 enum 타입이 있고 DB에 저장할때 enum값을 문자열로 저장하도록 JPA에 지시한다.

**Comment by erinleeme** [comment]
1. 단순히 우리가 사용할 DB가 RDMS라서 그런건 아닌데요, 다시 한번 확인해주세요~ 어떤 거를 사용해야할까용?
3. ERD를 보면 section은 enum 타입이 아닙니다. 어떤 타입을 사용하는 것이 좋을까요?

**Comment by ujgon** [comment]
1. @javax.persistence.Id 입니다.
2. Section, Position 클래스를 정의해서  Json문자열로 저장합니다?

**Comment by erinleeme** [comment]
JSON도 좋고 Section, Postion 클래스를 정의할거면 Array로 받거나 List로 받아서 사용하는 것도 좋아보이네요

**Comment by erinleeme** [comment]
- mappedBy는 어떻게 설정하는 것인지?
- JoinColumn은 무엇인지? JoinColumn을 사용할 때 Column 명은 어떻게 지정하는 것인지?
- cascade는 무엇인지?
- fetch 설정에서 FetchType.LAZY는 무엇을 의미하는 것인지?

내용들 정리하면서 코드를 어떻게 수정하는게 좋을지 한번 봐볼래? @ujgon

**Comment by erinleeme** [comment]
+ PostgreSQL에서는 User 이름의 테이블을 생성할 수 없어. 그래서 JPA를 통해 User Entity를 만들어 놓으면 에러가 발생해. 왜그럴까? 그러면 어떻게 할까~?

**Comment by ujgon** [comment]
> * mappedBy는 어떻게 설정하는 것인지?
entity끼리 양방향 관계를 가질때

> * JoinColumn은 무엇인지? JoinColumn을 사용할 때 Column 명은 어떻게 지정하는 것인지?
@JoinColumn 어노테이션은 외래 키 컬럼을 지정할때 사용
@JoinColumn (이름 =  외래키)

> * cascade는 무엇인지?
관계된 엔티티에 어떻게 전파될지 설정. PERSIST, MERGE, REFRESH 등이 있다

> * fetch 설정에서 FetchType.LAZY는 무엇을 의미하는 것인지?
entity 로드 타이밍 
Lazy는 지연로딩. 해당 엔티티를 사용할때
Eagar는 즉시로딩.

**Comment by erinleeme** [comment]
**다음 질문들에 대해서 노션 기록 페이지에 정리해 주세요.**

mappedBy는 어떻게 설정하는 것인지?
entity끼리 양방향 관계를 가질때
**-> 왜 모든 양방향 관계에 안붙이고 특정 관계들에만 붙일까요?**

JoinColumn은 무엇인지? JoinColumn을 사용할 때 Column 명은 어떻게 지정하는 것인지?
@joincolumn 어노테이션은 외래 키 컬럼을 지정할때 사용
@joincolumn (이름 = 외래키)
**-> 외래키 컬럼을 지정할 때 사용한다고 했는데 지정된 외래키가 해당 Entity에선 안보입니다.** 

cascade는 무엇인지?
관계된 엔티티에 어떻게 전파될지 설정. PERSIST, MERGE, REFRESH 등이 있다
**-> 전파된다는 것은 무엇을 의미하나요? PERSIST, MERGE, REFRESH에 대해서도 정리해 주세요.**

fetch 설정에서 FetchType.LAZY는 무엇을 의미하는 것인지?
entity 로드 타이밍
Lazy는 지연로딩. 해당 엔티티를 사용할때
Eagar는 즉시로딩.
**-> 지연로딩과 즉시로딩은 무엇을 의미하나요?**
